name: Build and Publish

on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  build-and-publish:
    uses: swatijha23/github_action_test/.github/workflows/Publish.yml@main
    with:
      node-version: 'lts/*'
      publish-to-npm: true
      s3-path: 'media-agents/browser/test'
      file-to-upload: 'dist/newrelic-video-dash.min.js'